<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9jinifx\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9jinifx/appProdProjectContainer.php') {
    touch(__DIR__.'/Container9jinifx.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container9jinifx\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container9jinifx\appProdProjectContainer([
    'container.build_hash' => '9jinifx',
    'container.build_id' => 'b179c7fe',
    'container.build_time' => 1627424606,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9jinifx');
